AWSTemplateFormatVersion: '2010-09-09'
Description: s3 event rule with batch job queue target

Parameters:
  BucketName:
    Type: String
    Default: raylayadi-test-bucket-asdf
  Vpc:
    Type: String
    Default: vpc-0f988868
  Subnet1:
    Type: String
    Default: subnet-11708877
  Subnet2:
    Type: String
    Default: subnet-0c3b5154

Resources:
  ###
  # Bucket
  ###
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  ### 
  # Batch Job
  ###
  ComputeEnvironmentServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'batch.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole'
  
  ComputeEnvironmentSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref Vpc
      GroupDescription: 'security group for batch compute environment'

  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      State: ENABLED
      ServiceRole: !GetAtt ComputeEnvironmentServiceRole.Arn
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 1
        Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
        SecurityGroupIds:
        - !Ref ComputeEnvironmentSg
  
  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref ComputeEnvironment
          Order: 1
      Priority: 1
      State: ENABLED

  JobExecutionRole:
    Type: AWS::IAM::Role
    Properties:
     AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
     ManagedPolicyArns:
     - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  JobTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ecs-tasks.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: BucketAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: [ 's3:GetObject', 's3:PutObject' ]
              Resource:
              - !Join ['', ['arn:aws:s3:::', { Ref: BucketName }, '/*' ] ]

  JobLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ '', [ '/', { Ref: 'AWS::StackName' }, '/log' ] ]
      RetentionInDays: 14

  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: { Ref: "AWS::StackName" }
      PlatformCapabilities:
      - FARGATE
      # Tags:
      #   aws:dlm:event-type:batch-job: true
      Timeout:
        AttemptDurationSeconds: 60
      RetryStrategy:
        Attempts: 1
      ContainerProperties:
        Command:
        - echo
        - hello
        - world
        Image: 'debian:latest'
        NetworkConfiguration:
          AssignPublicIp: ENABLED
        ResourceRequirements:
        - Type: VCPU
          Value: 0.5
        - Type: MEMORY
          Value: 1024
        JobRoleArn: !GetAtt JobTaskRole.Arn
        ExecutionRoleArn: !GetAtt JobExecutionRole.Arn
        LogConfiguration:
          LogDriver: awslogs
          Options:
            "awslogs-group": !Ref JobLogGroup
            "awslogs-stream-prefix": "prefix"

  ###
  # Lambda (additional target)
  ###
  HelloLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName:
            Fn::Sub: ${AWS::StackName}-HelloLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:*:*:*"
                

  HelloLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloLambdaFunction
      Role: !GetAtt HelloLambdaRole.Arn
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
            print(event)
            return message

  ###
  # Event Rule
  ###
  EventRuleTargetBatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  EventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      # Tags:
      #   aws:dlm:event-type:batch-job: true
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
            - !Ref MyBucket
          # object:
          #   key:
          #   - suffix: ".mp4"
      Targets:
        - Arn: !Ref JobQueue
          Id: batchjobqueue
          RoleArn: !GetAtt EventRuleTargetBatchRole.Arn
          BatchParameters:
            JobDefinition: 
              Ref: JobDefinition
            JobName: job
          # Input:
          #   !Sub
          #     - '{"Parameters": {"param1": "--param.name1=${param1}", "param2": "--param.name2=${param2}"}}'
          #     - param1: {param1_value}
          #       param2: {param2_value}
        - Arn: !GetAtt HelloLambdaFunction.Arn
          Id: lambda

  EventBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt HelloLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn